### ISSUE TITLE
Plugins installation references user_install version of neovim

### ISSUE THREAD

**Issue by kagux** [mkwmms/ansible-neovim#4]
If neovim is installed globally, then plugins installation fail as it tries to execute local binary

**Comment by mwilliammyers** [comment]
Thanks for the catch; it should be fixed in 884f23d. 

Also, I had to take out the whole `user_install` task because the method (using a pre-built binary) is not meant to be used by anyone besides neovim's build-bots and does not work. I will put something together that builds it from source when I get time.

**Comment by kagux** [comment]
Thank you for fixing the issue so fast!
